server:
  port: 8088
spring:
  application:
    name: rag-servicenow-chat
  ai:
    google:
      genai:
        api-key:            # your API key
        chat:
          options:
            model: models/gemini-2.0-flash
            temperature: 0.5

weaviate:
  scheme: http
  host: localhost:8080